<?php
/**
 * @file
 * Code to support logging comment activities using the messaging module.
 */

/******************************************************************************
 * Configuration
 ******************************************************************************/

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add messaging settings configuration to the node settings form.
 *
 * @see message_ui_comment_node_type_form_save()
 */
function message_ui_comment_form_node_type_form_alter(
  array &$form, array &$form_state, $form_id
) {
  $info = $form['#node_type'];
  $default_config = array();
  if (!empty($info->type)) {
    $default_config = variable_get(
      message_ui_comment_variable_name($info->type),
      array()
    );
  }

  if (empty($form['message_ui'])) {
    $form['message_ui'] = array(
      '#type' => 'fieldset',
      '#title' => t('Activity'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#group' => 'additional_settings',
    );
  }
  $form['message_ui']['message_ui_comment'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Log comment activity when'),
    '#description' => t('Select what comment activities should be saved in the message log.'),
    '#options' => array(
      'insert' => t('A comment is created'),
      'update' => t('A comment is updated'),
      'delete' => t('A comment is deleted'),
    ),
    '#default_value' => $default_config,
    '#weight' => 1,
  );

  $form['#submit'][] = 'message_ui_comment_node_type_form_save';
}

/**
 * Saves the type type specific message settings.
 *
 * @param array $form
 *   The form.
 * @param array $form_state
 *   The current form state.
 *
 * @see message_ui_comment_form_node_type_form_alter
 */
function message_ui_comment_node_type_form_save(array $form, array $form_state) {
  $values = $form_state['values'];

  // Save the configuration.
  variable_set(
    message_ui_comment_variable_name($values['type']),
    $values['message_ui_comment']
  );

  // Delete the old variable if the machine name has changed.
  if ($values['type'] !== $values['old_type']) {
    variable_del(
      message_ui_comment_variable_name($values['old_type'])
    );
  }
}

/**
 * Implements hook_node_type_delete().
 *
 * Delete the activity settings if the type type is deleted.
 */
function message_ui_comment_node_type_delete($info) {
  variable_del(
    message_ui_comment_variable_name($info->type)
  );
}

/**
 * Helper to determine if the type action needs a message or not.
 *
 * The config from the variables table is used to check if the given type type
 * requires messages.
 *
 * @param string $type
 *   The content type we want to log a message for.
 *   This supports also content types prefixed with the "comment_node_" prefix.
 * @param string $action
 *   The action performed on the type. The supported actions are:
 *   - insert.
 *   - update.
 *   - delete.
 *
 * @return bool
 *   Needs an message yes/no.
 */
function message_ui_comment_needs_message($type, $action) {
  if (!message_ui_comment_message_is_enabled()) {
    return FALSE;
  }

  // Cleanup types received from a comment.
  $type = preg_replace('/^comment_node_/', '', $type);

  $config = variable_get(message_ui_comment_variable_name($type), FALSE);
  if (!$config) {
    return FALSE;
  }

  if (empty($config[$action]) || $config[$action] !== $action) {
    return FALSE;
  }

  // Check if messages are deleted when the node is deleted.
  // If so => no message needed.
  $message_delete = variable_get(
    'message_delete_on_entity_delete',
    array('node', 'user', 'taxonomy_term', 'comment')
  );
  if ($action === 'delete' && in_array('comment', $message_delete)) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Helper to determine if a comment update needs a revision.
 *
 * This is different then message_ui_comment_needs_message() as this:
 *   1. Checks the configuration for the node type.
 *   2. Checks if there is an message within the last 6 hours.
 *   3. Checks if the last message type is one of the types we don't want
 *      duplicates for.
 *   4. Checks if that message is by the same user as the one updating the node.
 *
 * @param object $comment
 *   The comment that is being updated.
 *
 * @return bool
 *   Needs an update yes/no.
 */
function message_ui_comment_update_needs_message($comment) {
  if (!message_ui_comment_message_is_enabled()) {
    return FALSE;
  }

  // 1. Check config for the node type.
  if (!message_ui_comment_needs_message($comment->node_type, 'update')) {
    return FALSE;
  }

  // 2. Load the last previous message within the last 6 hours timeframe.
  $time_ago = strtotime(date('r', time()) . '-6 hours');
  $message = message_ui_comment_get_last_message($comment, $time_ago);
  if (!$message) {
    return TRUE;
  }

  // 3. Check if last message was one of the types we don't want to duplicate.
  $types = array('comment_insert', 'comment_update');
  if (!in_array($message->getBundle(), $types)) {
    return TRUE;
  }

  // 4. Check if the last message was for another user then the one
  // updating the comment.
  global $user;
  if ((int) $user->uid !== (int) $message->user->uid->value()) {
    return TRUE;
  }

  // No need for a message.
  return FALSE;
}

/**
 * Get the variable name to access the activity config per content type.
 *
 * @param string $type
 *   The content type.
 *
 * @return string
 *   The variable name.
 */
function message_ui_comment_variable_name($type) {
  return 'message_ui_comment_' . $type;
}


/******************************************************************************
 * Message logging
 ******************************************************************************/

/**
 * Create a message for a comment based on the given action.
 *
 * This will also save the message in the database.
 *
 * @param object $comment
 *   The comment that needs an message.
 * @param string $action
 *   The action performed on the node.
 *
 * @return object
 *   The saved message.
 */
function message_ui_comment_create_message($comment, $action) {
  $node = node_load($comment->nid);
  $group_nid = _message_ui_node_get_node_group($node);

  $arguments = array(
    '%comment_cid' => (int) $comment->cid,
    '!comment_uid' => (int) $comment->uid,
    '%node_nid' => (int) $node->nid,
    '!group_nid' => $group_nid,
  );

  $message = message_create(
    'comment_' . $action,
    array('arguments' => $arguments)
  );

  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->message_comment->set($comment);
  $wrapper->message_node->set($node);
  if ($group_nid) {
    $wrapper->message_group->set($group_nid);
  }
  $wrapper->save();

  return $message;
}

/**
 * Implements hook_comment_insert().
 *
 * Adds a node created message to the message table.
 */
function message_ui_comment_comment_insert($comment) {
  if (!message_ui_comment_needs_message($comment->node_type, 'insert')) {
    return;
  }

  message_ui_comment_create_message($comment, 'insert');
}

/**
 * Implements hook_comment_update().
 *
 * Adds a node updated message to the message table.
 * The message will only be created if the last insert/update of the node was
 * not done during the last 6 hours.
 */
function message_ui_comment_comment_update($comment) {
  if (!message_ui_comment_update_needs_message($comment)) {
    return;
  }

  message_ui_comment_create_message($comment, 'update');
}

/**
 * Implements hook_comment_delete().
 *
 * Adds a node deleted message to the message table.
 */
function message_ui_comment_comment_delete($comment) {
  if (!message_ui_comment_needs_message($comment->node_type, 'delete')) {
    return;
  }

  message_ui_comment_create_message($comment, 'delete');
}


/**
 * Get the last stored message for a given comment.
 *
 * @param object $comment
 *   The comment we want to load the message for.
 * @param int $time_ago
 *   The minimum timestamp the record must have to be included in the query.
 *
 * @return NULL | EntityMetadataWrapper
 *   Returns the node wrapped by EntityMetadataWrapper.
 */
function message_ui_comment_get_last_message($comment, $time_ago = 0) {
  $query = new entityFieldQuery();
  $query
    ->entityCondition('entity_type', 'message')
    ->fieldCondition('message_comment', 'target_id', $comment->cid)
    ->propertyOrderBy('timestamp', 'DESC');

  if ($time_ago > 0) {
    $query->propertyCondition('timestamp', (int) $time_ago, '>=');
  }

  $result = $query->execute();
  if (empty($result['message'])) {
    return NULL;
  }

  $message = entity_metadata_wrapper('message', key($result['message']));
  return $message;
}


/******************************************************************************
 * (Temporary) disable/enable activity logging.
 ******************************************************************************/

/**
 * Disable comment activity logging.
 *
 * The activity will only be disabled during the script execution.
 * It is not persistent over different requests.
 */
function message_ui_comment_message_disable() {
  $enabled = &drupal_static('message_ui_comment_status');
  $enabled = 0;
}

/**
 * Enable the comment activity logging (default state).
 */
function message_ui_comment_message_enable() {
  $enabled = &drupal_static('message_ui_comment_status');
  $enabled = 1;
}

/**
 * Check if the comment activity logging is enabled.
 *
 * @return bool
 *   Enabled (yes/no).
 */
function message_ui_comment_message_is_enabled() {
  $enabled = &drupal_static('message_ui_comment_status', 1);

  // By default enabled.
  if (is_null($enabled)) {
    $enabled = 1;
  }

  return (bool) $enabled;
}
